CommandHelp: Put all your spam items in the Mass Storage system. It can hold most simple, stackable items. Your storage space is limited, but you can buy more any time.
MaterialBlacklist:
- MAP
- POTION
- SPLASH_POTION
PermitNonStackingItems: true
DefaultCapacity: 1728
BuyCapacity:
  Amount: 1728
  DisplayName: Chest
  Price: 500
