CommandHelp: Put all your spam items in the Mass Storage system. It can hold most simple, stackable items.
PermitNonStackingItems: true
MaterialBlacklist:
- AIR
- BEDROCK
- BARRIER
- CHAIN_COMMAND_BLOCK
- COMMAND_BLOCK
- DEBUG_STICK
- ENCHANTED_BOOK
- FILLED_MAP
- KNOWLEDGE_BOOK
- LINGERING_POTION
- POTION
- REPEATING_COMMAND_BLOCK
- SPAWNER
- SPLASH_POTION
- STRUCTURE_BLOCK
- STRUCTURE_VOID
- TIPPED_ARROW
- WRITTEN_BOOK
- JIGSAW