CommandHelp: Put all your spam items in the Mass Storage system. It can hold most simple, stackable items.
PermitNonStackingItems: true
MaterialBlacklist:
- AIR
- BARRIER
- BAT_SPAWN_EGG
- BLAZE_SPAWN_EGG
- CAT_SPAWN_EGG
- CAVE_SPIDER_SPAWN_EGG
- CHAIN_COMMAND_BLOCK
- CHICKEN_SPAWN_EGG
- COD_SPAWN_EGG
- COMMAND_BLOCK
- COW_SPAWN_EGG
- CREEPER_SPAWN_EGG
- DEBUG_STICK
- DOLPHIN_SPAWN_EGG
- DONKEY_SPAWN_EGG
- DROWNED_SPAWN_EGG
- ELDER_GUARDIAN_SPAWN_EGG
- ENCHANTED_BOOK
- ENDERMAN_SPAWN_EGG
- ENDERMITE_SPAWN_EGG
- EVOKER_SPAWN_EGG
- FILLED_MAP
- FOX_SPAWN_EGG
- GHAST_SPAWN_EGG
- GUARDIAN_SPAWN_EGG
- HORSE_SPAWN_EGG
- HUSK_SPAWN_EGG
- KNOWLEDGE_BOOK
- LINGERING_POTION
- LLAMA_SPAWN_EGG
- MAGMA_CUBE_SPAWN_EGG
- MOOSHROOM_SPAWN_EGG
- MULE_SPAWN_EGG
- OCELOT_SPAWN_EGG
- PANDA_SPAWN_EGG
- PARROT_SPAWN_EGG
- PHANTOM_SPAWN_EGG
- PIG_SPAWN_EGG
- PILLAGER_SPAWN_EGG
- POLAR_BEAR_SPAWN_EGG
- POTION
- PUFFERFISH_SPAWN_EGG
- RABBIT_SPAWN_EGG
- RAVAGER_SPAWN_EGG
- REPEATING_COMMAND_BLOCK
- SALMON_SPAWN_EGG
- SHEEP_SPAWN_EGG
- SHULKER_SPAWN_EGG
- SILVERFISH_SPAWN_EGG
- SKELETON_HORSE_SPAWN_EGG
- SKELETON_SPAWN_EGG
- SLIME_SPAWN_EGG
- SPAWNER
- SPIDER_SPAWN_EGG
- SPLASH_POTION
- SQUID_SPAWN_EGG
- STRAY_SPAWN_EGG
- STRUCTURE_BLOCK
- STRUCTURE_VOID
- TIPPED_ARROW
- TRADER_LLAMA_SPAWN_EGG
- TROPICAL_FISH_SPAWN_EGG
- TURTLE_SPAWN_EGG
- VEX_SPAWN_EGG
- VILLAGER_SPAWN_EGG
- VINDICATOR_SPAWN_EGG
- WANDERING_TRADER_SPAWN_EGG
- WITCH_SPAWN_EGG
- WITHER_SKELETON_SPAWN_EGG
- WOLF_SPAWN_EGG
- WRITTEN_BOOK
- ZOMBIE_HORSE_SPAWN_EGG
- ZOMBIE_PIGMAN_SPAWN_EGG
- ZOMBIE_SPAWN_EGG
- ZOMBIE_VILLAGER_SPAWN_EGG
