name: MassStorage
description: Mass Storage for Spam Items
author: StarTux
version: 0.1
api-version: 1.13
main: com.winthier.massstorage.MassStoragePlugin
depend: [ SQL, Custom ]
softdepend: [ Vault ]
commands:
  massstorage:
    aliases: [ ms ]
    description: User interface
    permission: massstorage.ms
  massstorageadmin:
    aliases: [ msadmin, msadm ]
    description: Admin interface
    permission: massstorage.admin
    usage: |-
      /msadm reload - Reload configuration
      /msadm info <player> - Player info
      /msadm grant <player> <amount> - Grant player storage units
permissions:
  massstorage.ms:
    description: Use the /ms command
    default: op
  massstorage.admin:
    description: Use the admin command
    default: op
