main: com.cavetale.ms.MassStoragePlugin
name: MassStorage

version: 0.1
api-version: 1.19

description: Store massive amounts of items in the database
author: StarTux
website: https://github.com/StarTux/MassStorage

depend: [Core, SQL, Mytems]
softdepend: []

commands:

  ms:
    aliases: [massstorage]
    description: Access Mass Storage
    permission: massstorage.ms

  mss:
    aliases: [msi, massstorageinsert]
    description: Mass Storage Insert
    permission: massstorage.ms

  msadm:
    aliases: [massstorageadmin]
    description: Admin interface
    permission: massstorage.admin

permissions:

  massstorage.ms:
    description: Use /ms
    default: op

  massstorage.admin:
    description: Use /msadm
    default: op
