name: MassStorage
description: Mass Storage for Spam Items
author: StarTux
version: 0.1
api-version: 1.13
main: com.winthier.massstorage.MassStoragePlugin
website: https://cavetale.com
depend: [ SQL, Custom ]
softdepend: [ Vault ]
commands:
  massstorage:
    aliases: [ ms ]
    description: User interface
    permission: massstorage.ms
    usage: |-
      /ms - Open chest menu
      /ms <item> - Search items and offer in storage chest
      /ms store - Open storage chest
      /ms help - Get help
      /ms info - Get info about your mass storage
      /ms dump - Store your entire inventory
      /ms auto - Toggle automatic storage mode
      /ms find <term> - Search items and show info
      /ms buy <amount> - Buy additional storage space
  massstorageadmin:
    aliases: [ msadmin, msadm ]
    description: Admin interface
    permission: massstorage.admin
    usage: |-
      /msadm debug - Toggle debug mode
      /msadm reload - Reload configuration
      /msadm info <player> - Player info
      /msadm grant <player> <amount> - Grant player storage units
      /msadm category <category> - View category
permissions:
  massstorage.ms:
    description: Use the /ms command
    default: op
  massstorage.admin:
    description: Use the admin command
    default: op
